import cuid from 'cuid';

export default (options) => {
    options = options || {};

    if (options.constructor.name === 'IncomingMessage') {
        throw new Error('You might have used the module like `app.use(requestCuid)`, but it should be `app.use(requestCuid()`');
    }

    return function id(request, response, next) {
        // This will save the request-id if one has already been generated by a previous middleware or physical router and fallback to generating one, if it doesn't exist
        const requestId = request.get('x-request-id') || cuid();

        response.header('x-request-id', requestId);
        request.requestId = requestId;
        request.id = requestId;

        next();
    }
}